

class Dog:

    def __init__(self, description, personality, grooming, living_conditions, training, usefulness):
        self.description = description
        self.training = training
        self.personality = personality
        self.grooming = grooming
        self.living_conditions = living_conditions
        self.usefulness = usefulness


australian_shepherd=Dog(
    description="Description:\n",
    personality="Personality:\n",
    grooming="Grooming:\n",
    living_conditions="Living conditions:\n",
    training="Training:\nIt is an easy dog to train because it is intelligent, learns quickly and with pleasure. The training exercises must be done regulary and the dog must be kept busy as long as possible. Agility, flyball or training competitions are recommended.",
    usefulness="Usefulness:They are used, in the West of the United States, to lead and guard flocks or as companions. They can also be used as utility dogs to guide disabled people.\n")
belgian_shepherd_malinois=Dog(
    description="Description:\nIt is a dog with a well-proportionated, medium-sized, harmonious body, with strong muscles and an elegant look. The head is of medium length, with a muzzle of the same length as the skull and rather narrow at the top. The eyes are almond-shaped and dark brown. The ears are triangular, placed high, stiff, erect and medium-sized. The tail is of medium lenght and is carried low, the tip a little curved, with long, rich hair. The fur is made of short hair, slightly longer on the neck where it forms a collar and shorter on the head. It is reddish-yellow, with a black area around the muzzle.",
    personality="Personality:\nIt is an intelligent, active, jolly, watchful dog, devoted to its master. It is a rustic dog, used to living in the open. It is very resistant to weather changes. It is reserved with strangers and it gets along well with children. Some of these animals are aggressive with other dogs, but there shouldn't be a problem if they were socialized adequately.",
    grooming="Grooming:\nIt doesn't require too much grooming. A brushing during the shedding period is recommended.",
    living_conditions="Living conditions:\nIt is used to getting a lot of outdoor exercise. It likes long walks and any other activity that burns its energy. It needs an active master with experience in raising dogs. It needs socialization, training and exercise.",
    training="Training:\nIt is not hard to train because it is an obedient dog which learns pretty fast. It is an independent breed with a strong character and that is why they need training from an early age and getting accustomed to new things, people and animals. They must not be hit and a gentle, but firm tone should be used. Most of these dogs enjoy ball games, swimming, running beside a bike and long walks. They are successful in agility contests and flyball.",
    usefulness="Usefulness:\nUsed in the past to guard flocks, today this dog is used more as a companion dog and also for security and protection.")

mioritic_dog = Dog(
    description="Description:\nIt is a large-sized, strong, robust dog, without being heavy, with a well-developed body, with a wide and not too long chest.\nThe head is big, strong, massive, with the muzzle slightly shorter than the skull. The stop is not well pronounced, neither are the eyebrows.\nThe eyes are medium-sized, slanting, brown or hazel but never too light or yellow.\nThe ears are also medium-sized, set high, round ended and drooping.\nThey are not cropped. The tail is placed high, carried low, reaching the hock at rest; when alert it is carried high, over the backline, slightly bent, but never rolled on the back. It is bushy, well-covered with hair is not trimmed.\nThe fur is double-layered with a thick and soft inner layer. The outer layer is about 3.15-6.3 inch long (8-16 cm), thick, rough, resistant, slightly wavy, covering the whole body. The colours can be: pure white, pure grey, white with well-defined grey or black patches. It has a calm and intelligent expression.",
    personality="Personality:\nIt is an intelligent, jolly, active dog, well-balanced, calm, pretty flexible, friendly with almost everyone, especially children.\nIt is very devoted to its master and his family and will accept the family friends and other animals.\nThe Mioritic Shepherd is a one-master-dog. It is cautious with strangers.\nIt likes to be part of a family, to play with children, it doesn't know fear and is very brave.",
    grooming="Grooming:\nIt needs constant care. The brushing of the fur begins from an early age and it is done frequently (weekly), intensely especially during the shedding periods when it loses a lot of hair. This represents an inconvenient for those who wish to keep it indoors even though it is a good and peaceful companion.\nExcess hair between the footpads and in the ears must be removed.",
    living_conditions="Living Conditions\nIt is resistant to weather changes.\nIt doesn’t require an owner with too much experience in raising dogs. It has a medium level of activity, it doesn’t need consistent exercise.",
    training="Training:\nIt is not hard to train because it is obedient and eager to please its master. A gentle and consistent training can be done.",
    usefulness="Usefulness:\nIt is a good watchdog for herds and houses. It is a good companion dog, enjoying playing with children.")


airedale_terrier = Dog(
    description="Description:\n The Airedale Terrier is a large-sized, robust and wiry dog, with an elegant look.\nThe head is long, flat and conspicuous. \nThe eyes are small, dark and very expressive.\nThe ears are small, V-shaped and kept to the side, with the turn-over line slightly above the head.\nThe tail is kept erect almost vertical, and docked to two-thirds of its length.\nThe coat is double-layered with a short, hard, wiry, and slightly wavy without being curly outer layer.\nIt can be black,grey or fawn on the back (like a saddle).",
    personality="Personality:\nIt is an intelligent, brave, lively, quiet, active sometimes, playful and stubborn dog. Very devoted to its owner and patient with children. It accepts other household animals but tends to dominate other dogs if it wasn't taught to accept them. Is alert in the presence of strangers.",
    grooming="Grooming:\nThis dog doesn't require too much grooming. The fur will be trimmed twice a year. The fur between the paw pads of the feet will be cut when necessary.",
    living_conditions= "Living conditions:\nThe Airedale Terrier can rezist in bad weather and likes to live outdoors, in a large space, where it can get a lot of exercise, because it has a high level of activity. He needs training and socializing.",
    training="Training:\nIt is a relatively easy dog to train, because it is intelligent and eager to learn. The training must be consistent, firm, without being rough, and it should be varied so it won’t get bored, otherwise it will become very stubborn. It likes canine sports.",
    usefulness= "Usefulness:\nIt is used for hunting wild animals (otters, martens, foxes, rabbits, wild boars, bears). It is a good watchdog and in England it is widely used as a police dog. It is a pleasant companion dog.")

american_pit_ull_terrier= Dog(
    description="Description\nIt is a medium-sized, strong and muscular dog. It has a wide and short body, bigger in length than in height. The head is strong, broad, trapezoidal, with a long and wide muzzle but shorter than the skull (unlike the Amstaff). The cheeks, unlike those of the Amstaff, are flat. The nose is large and can have any color. The eyes are round and almond-shaped and can have any color except blue. The ears are small to medium and can be erect or semi-erect and can also be cropped. The chest is deep and less wide compared to the Amstaff. The rear legs are strong and muscular.\nThe tail is medium-sized, thick and with a pointed tip.\nThe coat is short, smooth, shiny and can have any color.",
    personality="Personality\nIs a confident dog with a tremendous taste for life. The Pitbull is very friendly with people, especially with children. It is so happy when given attention that it is willing to endure the toughest games of the children. It is unfriendly and aggressive with other dogs, especially to those of the same gender. It is the most controversial race of all, because friendly as it can be with people, it can become equally aggressive towards other dogs or other people it considers dangerous.",
    grooming="Grooming\nThis dog doesn't require special care. The dead hair will be removed with a rubber brush or glove, from time to time. The master should take care of how much the dog eats during the growing period, because it is prone to obesity. The meals should be served at fixed hours. ",
    living_conditions="Living conditions\nIt is a dog with a high level of activity and feels best in a fenced yard, with an active family, with experience in raising dogs.\nIt likes to run by a bike, to play with the ball, to play fetch, to swim and to dig. It can adapt to apartment life, if it gets the daily exercise that it needs (2-3 hours daily). It needs socializing and training (mandatory), because it has a dominant character and is harder to controle.",
    training= "Training\nIt needs mandatory training , starting from an early age. It must be taught not to pull when leashed when it is a pup, to avoid having problems when it grows up and has great strengh and is hard to control. It is an intelligent, nimble dog, which understands very fast what is required.\nThe training should start at an early age because it can assimilate much more information and great results can be obtained. \nt shouldn't be trained to attack, because it has an innate aggressive character.",
    usefulness="Usefulness\nIt was used during the World Wars as a messenger on the battlefield. Nowadays it is more used as a watchdog and as a pet.")

australian_terrier=Dog(
     description="Description:\nIt is a small-sized dog, with a rather longer than taller body.\nThe head is long, strong, with the skull equal in length with the muzzle, with a fine stop.\nThe eyes are small and dark.\nThe ears are small, with pointed tips, kept vertical, wide apart and with little hair on them but with a tuft of hair between them, on the forehead.\nThe tail is docked at half its length and is kept high, almost vertical.\nThe fur is double-layered, with a soft, fluffy first layer and an outer layer with long, rough, straight hair.\nAround its neck the hair forms a mane and it has furry legs.",
     personality="Personality:\nIt is a lively, active, clever, brave, alert, confident and curious dog by nature. Devoted and friendly to its family, it has trouble accepting strangers.\nIt gets along well with children if they do not bother it. It must be taught to live with other household animals from an early age, to avoid future conflicts.",
     grooming="Grooming:\nThis dog's fur must be brushed weekly and trimmed two-three times a year.",
     living_conditions="Living conditions:\nThese dogs can easily adapt to different living conditions, but they should have the possibility of running and playing together with a loving family.\nThey need socialization and training.",
     training="Training:\nIt needs a firm, consistent training, that doesn't let it have its way. It likes activity, walking, running and playing.",
     usefulness="Usefulness:\nIt is a very good pest hunter and a cheerful companion.")

australian_silky_terrier=Dog(
     description= "Description:\nIt is a small-sized, harmoniously built, robust dog that has an elegant look due to its silky hair. The head is of medium length, the skull is flat, slightly longer than the muzzle and has a fine forelock on the forehead. The eyes are small, round, almond-shaped and dark.\nThe ears are V-shaped, small, set high, erect and without long hair on them.\nThe tail is kept right and must be docked short.\nThe fur has a single layer made of 12-15 cm length hair that is very soft, glossy and silky.\nThe most common variety is the bluish-grey that can have different shades, from bright to dark, with brown, but the most appreciated and desired colour is iron blue.\nThe fur is brushed with a parting on the middle of the back.\nAt birth all the dogs of this breed are black.",
     personality="Personality:\nThis dog is dynamic, intelligent, eager to learn, active, lively, playful, cheerful, obedient, alert and although it is small it is very protective.\nVery devoted to its master it is loving and playful with children.\nIt is watchful with strangers whom it barks at. Accustomed from an early age to other household animals and to other dogs, it will have no problems when it grows up.",
     grooming="Grooming:\nThe fur must be brushed and combed daily in order to maintain it beautiful and healthy.\nThis breed rarely sheds.",
     living_conditions="Living conditions:\nThis dog adapts easily to the offered living conditions, being a suitable dog for a flat, with a loving and caring family.\nIt needs socialization and training.",
     training="Training:\nThe training should be done with ease and pleasure, because it is an intelligent and obedient dog that is eager to learn and easily understands what is required of it.\nIt has a medium level of activity, it likes not too long walks and doesn't become restless if it is not taken out for a walk every day.\nIt adapts to its master - more or less active.",
     usefulness="Usefulness:\nIt is a good mouse hunter but especially a happy and devoted companion.")

cairn_terrier=Dog(
     description="Description:\nIt is a small-sized, sturdy dog with short legs. It has a flat head, a pronounced stop, a strong muzzle and a black nose.\nThe eyes are wide apart, hazel and covered with bushy eyebrows. \nhe ears are small, triangular, slightly slating, pointy and erect. The tail is short, pointy at the tip covered in hair and carried vertically.\nThe fur is double-layered, with soft and fluffy inner layer and an outer layer made of thick, rough, not too short, straight hair.\nThe coat can have any colour except white and has darker shades on the ears, muzzle and the tip of the tail.",
     personality="Personality:\nIt is a lively, very happy, playful, alert, brave, intelligent, watchful dog. It is affectionate and devoted to its master. It is loving and tolerant with children and is not aggressive with strangers. It gets along well with other household animals, even with other dogs, with some exceptions.",
     grooming="Grooming:\nThis dog's fur must be brushed regularly and trimmed 2-3 times a year.",
     living_conditions="Living conditions:\nIt is a dog that can adapt rather easily both to outdoor life, being resistant to weather changes and to life in a flat with an active family and with the possibility of exercising and getting daily walks.\nIt needs socialization and training.",
     training="Training:\nThis dog is relatively easy to train because it is intelligent, likes to learn and to work. It needs a rigorous, firm, consistent training done in a gentle and calm voice and it shouldn't be let to do what it wants.\nIt should be socialized from an early age with other household animals and other dogs. It likes exercise and running in open spaces. It must be taught to come to its master when called, because of its hunting instincts that can make it run away.",
     usefulness="Usefulness\nIt is a very good hunter of rodents and small wild animals.\nIt is a perfect companion for a sportive family.")


west_highland_white_terrier=Dog(
    description="Description:\nIt is a small-sized, shapely, brawny dog that is tall rather than long. The head is wide compared to its length, it has a pronounced stop, covered with soft hair and a big, black nose. The eyes are medium-sized, round, dark and with thick eyebrows. The ears are small, pointed and erect. The tail is short up to 12-15 cm, pointy at the tip and carried straight, vertically. The fur is double-layered with an outer layer made of rough, straight, long (approximately 5 cm) hair. The fur on the face has a shaggy look and the muzzle gives the head a big and round look. The fur is pure white.",
    personality="Personality:\nIt is an intelligent, daring, curious, confident, brave, lively, playful, alert dog, but it can be stubborn and independent. It is loyal and attached to the family. It is suspicious of strangers, but a good playing partner for children. In general it gets along well with other dogs and other  household animals, but only if it was socialized from an early age, otherwise it can be dominant towards other dogs and small animals from the household can be considered prey (cats) and will be chased.",
    grooming="Grooming:\nThis dog's fur must be brushed and combed weekly to keep it neat. It must be trimmed 2-3 times a year.",
    living_conditions="Living conditions:\nIt is a dog that adapts to the offered living conditions - yard or flat, alongside an active master that has experience in raising dogs. It needs socialization, training and exercise.",
    training="Training:\nIt is a jolly, playful dog that is slightly stuborn with initiative and should not be let to do what it wants. The training must be firm, consistent, well-balanced, without being harsh or severe. It likes to play with the ball, to run and to dig, because of its high level of activity.",
    usefulness="Usefulness:\nIt was used in the past for hunting rabbits, foxes, or as a watchdog for the house, today being used more as a companion.")

scottish_sky_terrier=Dog(
    description="Description:\nIt is a small-sized, short dog, with a body twice as long as its height, but brawny. The head is proportional to the body, strong, with a black nose and covered with a silky forelock falling over its eyes. These are small, round, hazel. The ears are pointed, usually erect and covered by rich and long hair (may have drooping ears). The tail is docked short and carried straight. The fur is double-layered with a fluffy, soft, thick inner layer and an outer layer with long, straight, smooth, silky, glossy, rich hair, which falls on both sides of the body. It can be: black, grey, brown, yellowish, cream, with dark muzzle, ears and tip of the tail.",
    personality="Personality:\nIt is a brave and active dog outdoors, but calm, quiet indoors, intelligent and serious. It is loyal to the family and attached especially to one person. It accepts children, especially if they don't tease it. If they were socialized from an early age, they will have no problems with other animals and with other dogs when they grow up, although some specimens will sometimes have a dominant attitude towards other dogs. It is generally reserved with strangers.",
    grooming="Grooming:\nThe fur should be brushed, combed weekly, to keep it in good condition. The hair has a parting along the back. Excess hair in the ears and between the footpads should be removed.",
    living_conditions="Living conditions:\nThis dog can adapt to the outdoor life and also to a flat with a not too active master, but with experience in raising dogs. It needs socialization and training.",
    training="Training:\nThe training must be consistent, fair, well-balanced and firm without being cruel or harsh, even allowing some initiative to the dog. It likes long walks in different places (bridges, fields, parks).",
    usefulness="Usefulness:\nIn the past, they were used for hunting wild animals (foxes, badgers, otters). Today they are mostly used as pets and as watchdogs.")

scottish_terrier=Dog(
    description="Description:\nIt is a small-sized, pudgy, vigorous dog, with a rectangular look and short legs. The head is proportional to the body, long, conical, with the muzzle equal in length to the skull and with a beard. The eyes are almond-shaped, deeply set, set apart, dark and covered by bushy eyebrows. The ears are small, pointed, erect and with parallel outer edges. The tail is thick, conical, covered by short and rough hair, carried straight or slightly bent. The fur is double-layered with a fluffy, soft and short inner layer and an outer layer made of rough, wiry hair, black, straw-yellow or striped. The fur on the legs and belly touches the ground.",
    personality="Personality:\nIt is a dynamic, lively, active, brave, confident dog, but sometimes stubborn. Devoted and attached to the family, it is independent, harsh and suspicious of strangers. It accepts children if they don't bother it and leave it alone. Sometimes it can be aggressive with other dogs, but it gets along well with other household animals.",
    grooming="Grooming:\nThe chest, head and legs are generally trimmed. The rest of the fur must be combed weekly and trimmed 2-3 times a year. The beard and whiskers must be brushed daily, to remove leftover food.",
    living_conditions="Living conditions:\nIt is a dog which adapts easily to the offered conditions, outdoors or indoors, with  an active or less active master, but firm, determined, because it is a rather stubborn dog. It needs socialization and training.",
    training="Training:\nThe training of the dog must be done by a person with experience. It must be consistent, well-balanced, strong, done with patience because it is an independent dog.",
    usefulness="Usefulness:\nIt is one of the best hunting dogs for small animals of prey and foxes. It's a great companion.")

norwich_terrier=Dog(
    description="Description:\nIt is a small-sized dog, one of the smallest terriers, with strong legs, with a short and strong body. It has a broad and rounded head, with a strong, trapezoidal muzzle, shorter than the skull. It has small, dark eyes, set apart. The ears are small, with pointed tips and erect. Its head looks very much like a fox's. The tail is short, straight and carried vertically. The fur is double-layered, with a rough, smooth, hard, close to the body outer layer, longer on the neck and shoulders, almost like a mane and shorter on the head, muzzle and ears. The hair may be all shades of red, straw-yellow, black with brown.",
    personality="Personality:\nIt is a lively, non-aggressive, intelligent, alert, dynamic and daring dog, good and friendly but sometimes stubborn. It is affectionate and devoted to its master, it has no problems with children or with other dogs or other household animals. It announces strangers by barking and then calms down.",
    grooming="Grooming:\nThe hair must be brushed, combed regularly and trimmed 2-3 times per year.",
    living_conditions="Living conditions:\nIt is a dog which can adapt quite easily to the offered living conditions: in the open or in a flat, depending on its master - more or less active. It needs socialization and training.",
    training="Training:\nThis dog learns rather quickly, without any special problems during training if it is consistent, firm, well-balanced, without being harsh or cruel.",
    usefulness="Usefulness:\nIt likes walks and digging. It is rarely used to hunt small animals and more used as a pet.")

norfolk_terrier=Dog(
    description="Description:\nIt is a small-sized dog, with strong legs and a short, strong body. It has a broad and rounded head, with a strong, trapezoidal muzzle that is shorter than the skull. The eyes are small, egg-shaped, set apart and dark. The ears are drooping, slightly rounded at the tip and medium-sized. The tail is short, straight and carried vertically. The fur is double-layered, with an outer layer made of wiry, hard, smooth hair, of 3-5 cm long, longer on the neck and shoulders, where it forms a sort of mane. The hair on the head and ears is shorter than on the rest of the body. The eyebrows and moustache are of medium length. The coat can come in all shades of red, straw yellow, black with brown, with or without small white patches.",
    personality="Personality:\nIt is a lively, dynamic, brave, careful, intelligent, daring, friendly, firm and kind dog but can also be stubborn. It is affectionate and devoted to its master, it has no problems with children or with dogs or other household animals. Strangers are announced by barking after which it will calm down.",
    grooming="Grooming:\nThe hair must be brushed, combed regularly and should be trimmed 2-3 times per year.",
    living_conditions="Living conditions:\nIt is a dog that can easily adapt to the offered living conditions: in the open or in a flat, depending on its master - more active or less active. It needs socialization and training.",
    training="Training:\nThis dog learns pretty easily and no special problems will appear in the training if it is consistent, firm, well-balanced, without being harsh or cruel. It likes walks and digging.",
    usefulness="Usefulness:\nIt is rarely used to hunt small animals and more used as a companion dog.")

dachshund=Dog(
    description="Description:\nThe short-haired Dachshund is the most known from all breeds of Dachshund. It is a small sized dog, short, small and sturdy feet, a very long body, prominent chest with a pit on each side (as a bow of a boat). The head is oblonged, conical, the snout is a bit cambered. The eyes are medium sized, almond-shaped, egg-shaped and dark. The ears are long, round ended, flat, very mobile, caught up and hung it beside his head. The tail is long, thin, caught up and hanging down beside the head. The fur is short, straight, smooth, shiny and soft. It can be reddish-brown, black and more rarely are chocolate colour or tigerish.",
    personality="Personality:\nIt is an intelligent, lively, skilful, submissive, very brave dog, with a special olfactory sense, it is active, and persevering, curious and sometimes dominant. The family, in the middle of which it lives, it's on first place on its life, so attached is it of it. It is quite reserved with strangers.It must be socialized since an early age with children and with other dogs or other animals in the house otherwise, when it will grow up, its hunter instincts, will make it to play with another animal (especially the cat) in a hunt. Some specimens may have an attitude too brave, imprudence towards other bigger dogs.",
    grooming="Grooming:\nThe fur of this dog must be trimmed 2-3 times a year. The claws should be cut very short. Most of these dogs have the tendency to eat more, becoming obese. Ideal for them is to have 6,5-7 kg but they can arrive to 14 kg. An obese dog is a sick dog. Because of the very long spine they can have problems at the disks level between vertebras. They should not be allowed to climb stairs, to jump on a chair or to become obese. It is recommend using a mini harness instead of a dog-collar to protect the spine.",
    living_conditions="Living conditions:\nIt is an adaptable dog to the offered living conditions - open air or flat. The Dwarf variety is ideal for an apartment, on condition that to have the possibility to take exercises daily. It needs socialization and training.",
    training="Training:\nThe training of this dog must be made by a person with experience and preferably within a training session because it is a dog which has tenfencies of domination and an independent thinking. But with patience, with a positive, firm, consequent attitude, withoit being too severe (it suffers if it is punished) good result can be obtained and it learns a lot, even if it will not listen blindly always the commands. It needs exercise, walks, to run (the man should take care, because it can run if appears something which incites its hunter instincts) to keep its shapes.",
    usefulness="Usefulness:\nIt is an excellent hunter of small burrowing animals and even bigger animals (foxes, boars). It has a great perseverance in chaseing the prey and being able to resist 48 hours for its search. It is a good watchdog for the house and a devoted companion. It is used also in police to smell and to follow.")

dachshund_the_wiry_hair_variety=Dog(
    description="Description:\nThe only difference between the short-haired variety and this one, is represented by the fur. It has bushy eyebrows, moustache and a small beard and the head is covered with a double-layered fur, with a fluffy and soft inner layer and a very rough outer layer. The hair on the head and ears is shorter. The frequent colours are similar to those of wild animals; the black and fawn variety is rarely met. Dogs with red or chocolate-coloured fur can seldom appear.",
    personality="Personality:\nIt is an intelligent, lively, skillful, obedient, very brave dog, with a strong sense of smell, it is active and tenacious curious and sometimes dominant. The family, in the middle of which it lives, comes first in its life, due to its strong attachment. It is quite reserved with strangers. It must be socialized from an early age with children and with other dogs or other animals, otherwise, when it grows up, its hunting instinct can make it see playing with another animal (especially the cat) as a hunt. Some specimens may have an overly brave, uncautious behaviour towards other larger dogs.",
    grooming="Grooming:\nThis dog's fur must be trimmed 2-3 times a year. The claws should be cut very short. Most of these dogs have the tendency to eat a lot, becoming obese. The ideal weight for them is 6,5-7 kg but they can get to 14 kg. An obese dog is a sick dog. Because of the very long spine they can have problems with the intervertebral disks. They should not be allowed to climb stairs, to jump on a chair or to become obese. A mini harness is recommended instead of a dog collar to protect the spine.",
    living_conditions="Living conditions:\nIt is a dog that adapts to the offered living conditions - outdoors or indoors. The dwarf variety is ideal for an apartment, on condition that it has the possibility of daily exercise. It needs socialization and training.",
    training="Training:\nThe training of this dog must be done by a person with experience, preferably within a training school because it is a dog which has tendencies of domination and independent thought. But, with patience, with a positive, firm, consistent attitude, without being too severe (it suffers if it is punished) good result can be obtained and it learns a lot, even if doesn't always follow commands. It needs exercise, walks, running (the master should take care, because it can run off if something which incites its hunting instincts appears) to keep in shape.",
    usefulness="Usefulness:\nIt is an excellent hunter of small burrow animals and even of larger animals (foxes, boars). It has great perseverance in chasing the prey, being able to keep searching for even 48 hours. It is a good watchdog for the house and a devoted companion. It is also used by the police for tracking.")

long_haired_dachshund=Dog(
    description="Description:\nThe only difference between the Long-haired Dachshund and the short-haired Dachshund is the fur. This variety has soft, long, slightly wavy hair, longer on the neck, abdomen and ears and especially on the upper part of the legs and on the tail where it forms visible fringes. The fur is chestnut-coloured, reddish-brown, or black and brown.",
    personality="Personality:\nThe long hair variety is more gentle than the short hair variety. This dog is intelligent, lively, skillful, obedient, very brave, with a strong sense of smell, it is active, perseverant, curious and sometimes dominant. This dog is so attached to its family that the family is the most important thing in its life. It is quite reserved with strangers. It must be socialized with children and with other dogs or other household animals from an early age, otherwise, when it grows up, its hunting instincts will turn playtime with another animal (especially the cat) into a hunt. Some specimens may have an overly brave, careless attitude towards larger dogs.",
    grooming="Grooming:\nThis dog's fur should be brushed and combed when needed, in order not to get tangled. One should cut the excess hair between the footpads and should keep the claws short. Most of these dogs have a tendency towards eating more than they need, becoming obese. The ideal weight for them is 6,5-7 kg but they could weigh up to 14 kg. An obese dog is a sick dog. Because of the very long spine they can have problems with their intervertebral discs. They should not be allowed to climb stairs, to jump on a chair or to become obese. It is recommended to use a mini harness instead of a dog collar to protect the spine",
    living_conditions="Living conditions:\nIt is a dog that easily adapts to the offered living conditions - indoors or outdoors. The miniature variety is ideal for an apartment, on condition it has daily exercise. It needs socialization and training.",
    training="Training:\nThe long hair variety is slightly easier to train than the short hair variety, due to its more gentle character. The training is recommended to be made by a person with experience. Because it is an independent dog, the training must be done with patience, to be well-balanced and consistent. The dog needs movement and long walks to stay in shape.",
    usefulness="Usefulness:\nIt is an excellent small den animal hunter and even of larger animals (foxes, boars). It is perseverant in chasing its prey being able to resist 48 hours looking for it. It is a good watchdog and a devoted companion. It is also used by the police to track.")

akita_inu=Dog(
    description="Description:\nIt is a large-sized dog, strong, harmonious, brawny with a majestic appearance, that gives the impression of great distinction, due to its perfect symmetry. The body is slightly longer than taller, with a prominent and wide chest. The head is proportional with the body, flat between the ears, prominent stop, powerful and square jaws. The eyes are small, deeply set and dark brown. The ears are small, triangular, rounded and erect. The tail is medium in length, bushy and kept over the back or curled to the side. The double coat has a short, fluffy first layer and the second layer is made of short and straight hair. The coat can have various colors: red, white, brindled, grey, or black striped.",
    personality="Personality:\nIt is an intelligent, proud, pretty brave, obedient, well-balanced, imperturbable dog with a strong hunting instinct. It doesn't bark too much and it sometimes is independent and even dominant. Very devoted to its master, it is protective with children and accepts them if they don't provoke him. They are cautious and suspicious with strangers. They need to be socialized at an early age with other dogs and other animals in the household to avoid becoming dominant at maturity (especially towards dogs from the same gender).",
    grooming="Grooming:\nThe coat requires a more intense brushing during the shedding period to remove dead hairs. Otherwise a casual brushing is enough.",
    living_conditions="Living conditions:\nIt is a dog that can withstand the cold weather and feels better outdoors next to an owner with experience in raising dogs. It needs an eclosure so it won't go hunting when it catches the scent of potential prey. The dog should wear a muzzle when it goes out on the street to prevent it from attacking other dogs (if it hasn't been socialized enough).",
    training="Training:\nThe training must be done by someone with experience, confident and must be firm, consistent and varied so the dog won't get bored. It is an intelligent dog and beautiful results can be achieved. It needs to be socialized at an early age with children, people, dogs and other animals. It has a medium level of activity and it likes to take long walks.",
    usefulness="Usefulness:\nThis breed became very popular due to the touching story of an Akita dog, named Hachiko which used to accompany its master daily to the train-station and back. Unfortunately the owner died at work, but the dog continued all its life to welcome that particular train, hoping that one day its master will arrive.")

swedish_wallhund=Dog(
    description="Description:\nIt is a small to medium-sized dog, with short legs, a brawny and long body and a broad and deep chest. The head is broad, triangular shaped with a conical muzzle and with a black nose. The eyes are medium-sized, oval and dark hazel. The ears are medium-sized, triangular, pointy, erect and mobile. The tail is short, about 10 cm long and kept horizontally or slightly lower. The fur is double-layered, with a fluffy, short, thick inner layer and a short, rough, thick outer layer. The colour of the coat can be gray with black strands or reddish-yellow with lighter areas. Brindle, spotted, grey brown, or yellow brown specimens can also be met. Small white spots cover up to 1/3 of the body.",
    personality="Personality:\nIt is a watchful, active, alert, intelligent, brave, dynamic dog, eager to learn (with characteristics similar to the herding dogs). Devoted and attached to the family, it is protective and loving with children, always protecting them from strangers who try to get to close. It is reserved with strangers. It gets along well with other dogs and other household animals.",
    grooming="Grooming:\nThis dog's fur needs regular brushing in order to be kept in good condition.",
    living_conditions="Living conditions:\nIt is a dog resistant to bad weather, which likes to live outdoors with an active family. It can also adapt to living in a flat, if it has the possibility to burn its energy. It is a dog that needs lots of activity, socialization and training.",
    training="Training:\nIt is an easy to train dog because it is intelligent and eager to learn. With a consistent, firm, varied and gentle training, beautiful results can be obtained. It loves to train for agility contests or other canine sports.",
    usefulness="Usefulness:\nIt is a herding dog, a watchdog and a devoted companion.")

norwegian_elkhound=Dog(
    description="Description:\nIt is a medium-sized dog, with a square shape and a stocky and powerful body. The head is broad and slightly rounded with a medium-sized, conical muzzle. The eyes are medium-sized, oval, and dark. The ears are medium-sized, triangular, pointed, erect and very mobile. The tail is slightly curved, carried on its back and covered with thick, long hair. The fur is double-layered with a thick, wolly, beige inner layer and an outer layer made of rough, thick and long hair, which forms a mane around the neck. It has different shades of grey, dark to black behind the ears and around the muzzle. There are varieties with black fur but they are considered an independent breed. In this case they may also have white patches on the chest and paws.",
    personality="Personality:\nThis dog is very brave, intelligent, bold, very strong, lively, but it can be independent and stubborn. Devoted and sensitive with its master, it accepts children, if they don't tease it. It announces the strangers, being reticent with them. It accept other dogs, but sometimes it may be dominant (less often, but it is happening). It must be socialized with other small animals from household to not treat them as a wild game.",
    grooming="Grooming:\nThis dog's fur requires a more intense brushing during the shedding period.",
    living_conditions="Living conditions:\nThis dog is resistant to weather changes and feels best in the open, in a colder climate. It can adapt indoors, but it needs daily exercise and running. Care should be taken to prevent it from running away, following a scent. It needs socialization and training.",
    training="Training:\nIt must be trained by a person with experience, because it is an independent and stubborn dog. The training must be firm, consistent and well-balanced without being harsh, severe, or involving punishments.",
    usefulness="Usefulness:\nIt is still used for hunting large animals, sometimes as a watchdog or as a companion dog")

dalmatian=Dog(
    description="Description:\nIt is a large-sized, strong, brawny dog, with symmetrical lines and with a square shape. The head is medium-sized, rather long, the skull is flat, broader between the ears, it has a strong muzzle with a big, black or brown nose, the same colour as the spots. The eyes are round, medium sized, hazel or blue. The ears are placed high, medium-sized, with pointed and folded tips. The tail is long, conical, with the tip slightly bent. The fur is short, smooth, soft, thick and glossy. The coat is white with round spots that don’t overlap. Due to its coat, it is the most easily recognizable breed.",
    personality="Personality:\nIt is an intelligent, active, fast, well-disciplined, energetic dog, friendly and sometimes stubborn. It was created to catch pests (mice, rats). Today it is a good watchdog and a pleasant companion. Devoted and friendly to its master, tolerant and loving with children (it being a big dog, care should be taken when it plays with children) it is cautious and vigilant with strangers. It gets along well with other dogs and other household animals (it has an innate affinity for horses).",
    grooming="Grooming:\nThis dog's fur needs a more frequent brushing during the shedding period. For the rest it doesn't shed much.",
    living_conditions="Living conditions:\nIt is a dog with a high level of activity which likes to have space to move freely, to live with to an active master with experience in raising dogs. Is a large-sized dog and it's hard to keep in a flat, but it can adapt, if it gets its daily exercise (long walks, running by a bicycle, in wide open spaces, swimming, playing).",
    training="Training:\nIt needs a firm, consistent, well-balanced training that must be done with a lot of patience to overcome potential stubbornness.",
    usefulness="Usefulness:\nIt is a good watchdog and an elegant and pleasant companion.")

rhodesian_rodgeback=Dog(
    description="Description:\nIt is a medium to large-sized dog that is strong, well-built and brawny. It is long rather than tall, it has a big head with a long, thick and strong muzzle and a big, black nose. It makes wrinkles on the forehead when alert. The eyes are black, brown or amber. The ears are set high, V-shaped, drooping close to the head and darker than the fur. The legs are strong with large shoulders compared with the rest of the body. The tail is long, thick and pointy at the tip. It has a strong pigmentation on the nose, pads, eyelids and claws. The fur is short, smooth, glossy, flat, rough and can come in different shades of golden, wheat-coloured, reddish or brownish. It can have small white patches on the chest or toes. It generally has a black mask around the muzzle and eyes. This dog has a distinctive crest on its back of approximately 5 cm (2 inches), hair that grows in the opposite direction from the rest.",
    personality="Personality:\nIt's an intelligent, brave, watchful, quiet but independent dog. It is devoted to its family and gets along well with children if they don't tease it. It is careful with strangers, and having a hunting instinct it can't be trusted around small animals. If socialized from an early age with cats, other dogs and other household animals, it will accept them and there will be no problems when it grows up.",
    grooming="Grooming:\nThis dog's fur is kept beautiful through a regular brushing once or twice a week and in the shedding period it a rubber brush can be used to remove dead hair and to keep the fur glossy.",
    living_conditions="Living conditions:\nThis dog is resistant to bad weather and feels best outdoors in a well-fenced yard where it can move freely. It can also adapt in a flat, but it must be taken out daily, at least one hour/day. It has a medium level of activity, so after it has consumed its energy, it will stay quiet in the house. It likes to take long walks, to run by a bike. It needs socialization and training from an early age and a leash when it grows up.",
    training="Training:\nThe training must be consistent but gentle. These dogs are intelligent, understand fast what is required, but are a little stubborn, so they need a master with a strong character.",
    usefulness="Usefulness:\nIn its country of origin is used as a hunting dog (especially for lions). It is an excellent watchdog, but also a good companion dog.")

basset_fauve_de_bretagne=Dog(
    description="Description:\nIt is a small- to medium-sized dog, long rather than tall and rather strong. It has a long skull, a rectangular to conical muzzle with a big and dark-brown nose. It has long ears, with pointed tips, drooping and covered with delicate, soft hair. The tail is thick at the base, medium-sized in length and shaped like a sickle. The fur has rough, thick, almost straight hair, of medium length. It has a golden colour, light or dark reddish and possibly with a white patch on its chest and neck.",
    personality="Personality:\nIt is an intelligent, bold, brave and perseverent dog with an excellent sense of smell, active, cheerful and friendly. Jolly and friendly with its master, it accepts children and it has no problems with strangers either. It gets along well with other dogs. Other animals are not a problem, as long as the dog is used to them from an early age.",
    grooming="Grooming:\nThis dog's fur needs regular brushing and trimming about twice a year.",
    living_conditions="Living conditions:\nThe dog feels best outdoors, in an enclosed yard where it can exercise, but it can also adapt to an apartment with an active familiy if long daily walks are provided. It has the tendency, like all hunting dogs, to wander off chasing a scent. It needs socialization and training.",
    training="Training:\nWith a gentle, but consistent training performed with patience, the desired results are achievable. It must be taught to respond to calls from an early age in order to avoid its walking away on its own.",
    usefulness="Usefulness:\nIt is an excellent hunting dog for rabbits and a pleasant companion.")

gordon_setter=Dog(
    description="Description:\nIt is a medium- to large-sized dog, brawny, robust, but elegant. It has a strong head, a slightly rounded skull, a prominent stop, a long and rectangular muzzle, with a broad and black nose. The eyes are egg-shaped, medium-sized, dark hazel. The ears are placed low, medium-sized, round- ended and drooping. The tail is rather short, conical, straight or slightly bent, carried horizontally or below the backline. The fur has smooth or slightly wavy hair, of medium length, silky, black with chestnut patches. The fur is richer and forming fringes on the ears, belly, chest, neck and the back side of the legs.",
    personality="Personality:\nIt is an intelligent, hardworking, enthusiastic, affectionate, sociable, gentle and independent dog. It is obedient and devoted to its master, loving and gentle with children, cautious with strangers. If socialized from an early age with other dogs and with other animals, there will be no special problems when it grows up.",
    grooming="Grooming:\nThis dog's fur must be brushed and combed regularly. Excess hair in the ears should be removed, to keep the auditory duct clean and to avoid infection.",
    living_conditions="Living conditions:It is a dog with a high level of activity which likes to take a lot of exercise and keep busy. It is recommended to active people who can take time to take care of the dog because it likes to roam, to take long walks, to run by a bicycle, after reaching maturity. It can also be kept in a flat, if given the necessary conditions, because it is a large-sized dog that needs physical and psychological daily exercise to keep it calm indoors. Is feels best in a well-fenced yard, where it can move freely. It needs socialization and training.",
    training="Training:\nIf its independent side is taken into consideration, the training of this dog must be firm, consisteFnt, well-balanced but without being severe and done in a soft, affectionate voice.",
    usefulness="Usefulness:\nIt is used for bird hunting, especially woodcocks and as a watchdog for the house. It is a pleasant companion.")

weimaraner=Dog(
    description="Description:\nIt is a big sized dog, brawny, strong, robust. The head has medium length, the snout is equal with the skull and the nose has the skin colour (grey or brown). The eyes are medium sized, egg-shaped, spaced grey or hazel. The ears are placed above, are long and wide and round ended. The tail is cut short and carried upped, almost vertically. The fur may be shorter or longer (there are two varieties) and have silver-grey or brown colour. The short hair is fine, bushy and well adhered to the body. The long hair (rarely met) is silky and slightly wavy, velvety on ears and longer on the neck and chest.",
    personality="Personality:\nIt is an intelligent, dynamic, hardworking, friendly dog, with a high resistance, it is watchful, sometimes stubborn. It is submissive and devoted to its master, protective and friendly with the children, watchful and cautious with the strangers. Socialized since an early age with other dogs and other animals it will have no problems.",
    grooming="Grooming:\nAt the short hair variety, a casual brushing with a rubber brush is enough. At long hair variety the brushing and the combing must be made regularly.",
    living_conditions="Living conditions:\nIt is a dog with a high level of activity which likes to make much exercise and to have permanent occupation. It is recommended for the active persons and who can make time for the dog. It has ambitions for canine sports, it likes to swim, to run in open space, to play fetch, to take long walks. It could be kept in a flat if there are conditions, because it is a big sized dog and needs daily exercise for its physical and mental health, but it feels better in a fenced yard where they can move freely. It needs socialization and training.",
    training="Training:\nThe training must be firm and consistent because of its tendency to do anything it wants, but is eager to make pleasure to its master and will be not very difficult to train.",
    usefulness="Usefulness:\nIt is first a good hunting dog in any field (land or water) and for any game. It's a good watchdog for house and a pleasant companion.")

wetterhoun=Dog(
    description="Description:\nIt is a medium-sized, brawny, but not heavy dog. It has a strong head, proportional to the body, the skull is slightly rounded, wide rather than long, with a strong muzzle and a flat, black or brown nose. The eyes are medium-sized, egg-shaped, slightly slanting, light or dark brown. The ears are of medium length, wide, drooping, covered with long and curly hair at the base and very short hair at the tips. The tail is rolled in a spiral, arched above the thigh. The fur is made of curly, oily, dense, thick hair. On the head, the hair is short and smooth. It can be pure black, fawn, black with white, fawn with white and tricoloured.",
    personality="Personality:\nIt is an intelligent, courageous, curious dog, eager to know and see everything, sensitive, watchful, friendly to people it knows and somewhat independent. It is obedient and devoted to its master, loving and patient with children if they don't bother it, watchful and cautious with strangers. It accepts other dogs and other household animals.",
    grooming="Grooming:\nThe fur needs a casual brushing. The ears will be kept clean.",
    living_conditions="Living conditions:\nThis dog is resistant to weather changes and feels best outdoors in a fenced yard that it will always guard and where it can move freely. It adapts with difficulty to a flat. It is a dog which likes to be busy, to exercise, to run and to swim. It needs training and socialization.",
    training="Training:\nBecause it is sometimes independent, the training must be firm, consistent, friendly and gentle, keeping in mind that it is a dog that learns easily and is rather friendly.",
    usefulness="Usefulness:\nIt is a good hunting dog, a good watchdog and a devoted companion.")

welsh_springer_spaniel=Dog(
    description="Description:\nIt is a medium-sized, harmonious and strong dog, with a symmetrical constitution. The skull is slightly rounded, the muzzle is of medium-sized length, straight, square and it has a brown or black nose. The eyes are medium-sized, oval and dark brown. The ears are placed at the eyeline, have medium length, kept drooping, leaflike. The tail can, or not be docked and is carried horizontally or slightly higher. The fur has medium length, soft hair, longer on the chest, abdomen and legs and short on the head. It is red, with white and red freckles.",
    personality="Personality:\nIt is an intelligent, gentle, sociable, quiet, friendly dog. It is loyal and obedient to its master, affectionate and patient with children and friendly even with strangers. It gets along well with other dogs and other animals",
    grooming="Grooming:\nThe fur needs regular brushing and combing and a professional trimming 3-4 times a year. The excess hair between the footpads and ears should be removed, not to block the ear canal.",
    living_conditions="Living conditions:\nIt is a dog that easily adapts to the offered conditions - outdoors or in an apartment, on condition it gets daily exercise, because it's a dog with a high level of activity. It likes long walks, running, playing and swimming. If it catches an interesting scent it can leave its master's side or the yard if not well enclosed.",
    training="Training:\nThis dog is easy to train, because it understands easily what is required of it. To get the desired results, the training must be consistent, gentle, encouraging, the dog being very sensitive to its master's voice. It has to be taught to come when called not to leave by itself.",
    usefulness="Usefulness:\nIt is an excellent grubber and fetcher in bird hunting, even in frozen waters. It is a cheerful and pleasant companion.")

clumber_spaniel=Dog(
    description="Description:\nIt is a medium-sized, massive, heavy dog, long rather than tall, with very short legs. It has a big and square head, a short muzzle and a large nose of different shades of brown, pink or purple. The eyes are big, round and amber-coloured. The ears are big, wide, long (shaped like a vine leaf), drooping and well covered with hair. The tail is docked short. The fur is of medium length, it is thick, straight, silky with fringes on the ears, neck, abdomen and legs. It is white with yellow or orange patches.",
    personality="Personality:\nThis dog is intelligent, courageous, tenacious, friendly with the ones close to it, well-balanced, quiet, with a good memory and with a noble character. It is affectionate and devoted to its master, it accepts children but is reserved or even unfriendly with strangers. It gets along well with other dogs and other household animals.",
    grooming="Grooming:\nThe fur must be combed and brushed frequently. The hair on the ears must be trimmed, in order not to block the ear canal.",
    living_conditions="Living conditions:\nIt is a dog that feels good with a loving and active family. Although it has a moderate level of activity, it likes to take walks, to practice field sports, but it can adapt to the family and conditions offered. It is quiet and calm indoors, even if it is a rather active dog. It needs socialization and training.",
    training="Training:\nThis dog's training is not difficult, because it is an intelligent dog, with a good memory and wants to please its master. With a consistent, gentle training, one can easily obtain good results.",
    usefulness="Usefulness:\nAlthough fit for it, today it is rarely used for hunting birds, being mostly used as a watchdog or as a companion dog.")

curly_coated_retriever=Dog(
    description="Description:\nIt is a medium- to large-sized dog, well built, strong, long rather than tall. It has a long, big skull, with a trapezoidal muzzle equal in length to it and a black nose. The eyes are quite big, brown or black. The ears are relatively small, covered with curly hair, pointed and drooping. The tail is conical, of medium length, covered with curly hair, kept high up to the backline. The fur is waterproof, curly, except for the face and the legs and is black or dark red to brown.",
    personality="Personality:\nThis dog is intelligent, energetic, jolly and noisy. It is obedient and devoted to its master, loving and patient with children if they don't annoy it too much, it is pretty cautious with strangers. Generally it gets along well with other dogs and other animals from the household.",
    grooming="Grooming:\nThe fur will be brushed during the shedding period to remove dead hair, but not too hard not to destroy the texture of the fur. Sometimes, after brushing, the fur can be sponged wet to make it curly again. If it grows too long it can be slightly trimmed.",
    living_conditions="Living conditions:\nThis dog is resistant to weather changes, it has a rather high level of activity, it likes to exercise, to be kept busy, otherwise it can become disobedient. It likes canine sports, especially field ones, swimming and playing fetch. It feels best in a fenced yard where it can move freely. It needs socialization and training.",
    training="Training:\nWith a firm, consistent, varied training, without being rough or severe, one can obtain good results soon enough, because this dog is intelligent, it understands quickly and wants to please its master, even if it has an independent side and males are more dominant than females.",
    usefulness="Usefulness:\nIt's a hunting dog that does well on any field, a good watchdog and a lovely companion.")

shih_tzu=Dog(
    description="Description:\nIt is a small-sized, strong, well balanced, robust dog, which is rather long than tall. It has a massive and round head, the skull is flat between the eyes, with a square, short, flat muzzle and a black nose. The head is covered with rich hair forming whiskers and a beard. The hair growing on the nose points upwards, giving it a chrysanthemum look. The eyes are big, round and dark. The large drooping ears are covered with so much thick hair that it seems to blend into the hair on the neck. The tail with long, thick hair is carried rolled up on its back. It has a double-layered fur with an outer layer made of long, thick, slightly wavy hair and a soft, fluffy inner layer. It can be any colour or combination of colours with a white stripe on the forehead and a little white patch on the tip of the tail.",
    personality="Personality:\nIt is an intelligent, jolly, gentle, active, proud, dignified, alert dog, somewhat stubborn and independent but friendly with everyone. It is affectionate and devoted to its master, friendly and sociable with children, cautious around strangers. It gets along well with other dogs and other household animals.",
    grooming="Grooming:\nThe fur needs daily brushing to avoid getting tangled. The hair on the nose and forehead will be tied not to cover its eyes. This breed has very sensitive eyes and they must be kept clean at all times, by using special eye-drops. The ears will also be checked regularly and kept clean. Those who have no time to groom the dog, can have it trimmed every two months. The hair is combed with a parting on the back.",
    living_conditions="Living conditions:\nIt is a dog which feels very well in an apartment with a careful, loving and caring master. It has a low level of activity and is happy with short walks. It needs socialization and training.",
    training="Training:\nIt needs a consistent, rather firm training, done with patience, without being severe.",
    usefulness="Usefulness:\nIt is a pleasant companion dog.")

brussels_griffon=Dog(
    description="Description:\nThey are small-sized dogs, with short and strong bodies. They have a large, broad and round skull, a curved forehead, a short muzzle, powerful jaws, a black, short nose placed deep between the eyes. It has big, black, round eyes, prominent and set apart. The ears are semi erect and can be cropped to stay erect. The tail is docked to a third of its natural length and kept low. The Bruxelles Griffon has rough, medium length, thick, bristling hair, forming beard and whiskers on the face. It can be pink-red, sometimes with black on the nose and beard. The Belgian Griffon has rough, medium length, thick, bristling hair, forming beard and whiskers on the face. It can be completely black, reddish and black or red. The Barbacon Dwarf has short hair, no beard or moustache and has the same colours as the other Griffons.",
    personality="Personality:\nThese dogs are calm, eager to learn, lively, jolly, playful, even restless, curious and sociable. They are devoted to their master, affectionate and playful with children, but suspicious of strangers. They get along well with other dogs and other household animals",
    grooming="Grooming:\nThe wiry fur of the Griffons should be trimmed by hand regularly, leaving the moustache, beard and the rest of the hair on the face untrimmed. The whiskers and beard should be cleaned of food scraps and kept untangled. Also, it is required to remove the hair from the corner of the eyes, not to irritate them.",
    living_conditions="Living conditions:\nThey feel well in an apartment or in a house with a loving master. Even if they have a moderate level of activity, they enjoy occasional longer walks and canine sports. They need socialization and training.",
    training="Training:\nWith a well-balanced, varied, gentle training the desired results can be obtained, because they are intelligent and eager to learn dogs.",
    usefulness="Usefulness:\nThey are pleasant and cheerful companions.")

cavalier_king_charles_spaniel=Dog(
    description="Description:\nIt is a small-sized, well-balanced, well-built and graceful dog. The head is relatively flat between the ears, with a not too prominent stop, a conical muzzle and a black nose with large nostrils. The eyes are big, round, spaced and are dark. The ears are set high, very long, drooping and covered with rich fringes. The tail is quite long, kept low, well covered in fur and can be docked at 2/3 of its length. The fur is of medium length, with silky, straight or a bit wavy hair, with rich fringes on the ears, tail and the back side of the legs. It can be white with brown patches (Bleiheim), black, reddish, black with fawn, or tricoloured (black, white and fawn).",
    personality="Personality:\nIt is an active, lively, gentle, intelligent, sociable and friendly dog. It is obedient and devoted to its owner, friendly with children, it gets along well with other animals and other dogs.",
    grooming="Grooming:\nThe fur should be brushed regularly to avoid getting tangled and to remove dead hair. The ears will be kept clean. They are a little greedy with food and are predisposed to obesity.",
    living_conditions="Living conditions:\nIt is a dog that can easily adapt to any living conditions and lifestyle offered by its master. It has a low level of activity and will be satisfied with short walks, but it will not refuse a longer walk. It needs socialization and training.",
    training="Training:\nIt is a dog that understands pretty easily what is required and is eager to learn, therefore is not hard to train. With a consistent, gentle training the wanted results can be achieved.",
    usefulness="Usefulness:\nIt is a pleasant companion dog.")

scottish_deerhound=Dog(
    description="Description:\nIt is a large-sized, strong dog, with a broad head, wide and flat between the ears, it has a cone-shaped muzzle, adorned with a moustache and a beard and its nose is black. The eyes are medium- sized, dark or hazel. The ears are set high, small, soft and they are slightly folded back when at rest and raised when in action. It has a long and strong neck. The tail is long, almost touching the ground and kept low when at rest and high in movement. The coat has medium length hair, rough and wiry, slightly longer on the belly, chest and head. The most common color is dark-blue, grey but it can be yellow, light grey, red, brown, or red mixed with white and black. It can have white spots on the chest and paws.",
    personality="Personality:\nIt is an intelligent, brave, gentle, even-tempered dog that rarely barks. It is affectionate, devoted to its master, gentle with children, mildly alert to strangers. It has a powerful hunting instinct which can cause problems with other animals.",
    grooming="Grooming:\nThis dog's fur must be brushed regularly, and if needed, it will be trimmed by hand once or twice per year. The excess hair from the ears and from between footpads will be removed.",
    living_conditions="Living conditions:\nIt feels well in an enclosed yard where it can run freely but it can also adapt in a large house if its daily need of exercise is met. It likes to run in open space or alongsde a bicycle. It has a strong hunting instinct and it might run after game, leaving its master if not controlled. It needs trainig and socializing.",
    training="Training:\nWith a consistent, gentle, friendly training, good results can be achieved.",
    usefulness="Usefulness:\nIt is used for hunting large wild animals (deer, antelopes) and as a companion dog.")

irish_wolfhound=Dog(
    description="Description:\nIt is a large-sized, brawny, sturdy dog but with supple movements.\nIt has a long head, the skull is not too wide with a long, slightly pointed muzzle and a black nose.\nThe eyes are oval, medium-sized and dark. The ears are small, delicate and folded in the shape of a rose. It has a long, brawny, strong neck. The tail is long, slightly bent and of medium thick.\nThe fur is double-layered with a short and fluffy inner layer, and an outer layer that has medium length, thick, rough, pointy, wiry hair that is slightly longer on the head where it forms eyebrows and a bit of beard.\nThe colour of the coat can be grey, red mixed with white and black, reddish, black, light brown and white.",
    personality="Personality:\n It is an intelligent, brave, dynamic, sensitive, peaceful dog.\nIt is affectionate and very attached to its master and his family, patient with children and pretty friendly with everyone.\nIf it is socialized from an early age, it will have no problems with other dogs and other animals.\nIt barks very little.",
    grooming="Grooming:\nThis dog's fur must be brushed and combed regularly.\nAlso, once or twice a year it will be trimmed to remove excess hair.\nDuring the growing period it should be properly fed and shouldn't be forced to exercise more than it wants.\nIt finalizes its growth at the age of 2 years.",
    living_conditions="Living conditions:\nIt is a dog which adapts to the offered conditions, but it feels best outdoors in a well-fenced yard where it can move freely.\nKept in a house or in a spacious flat (it is a large and tall dog), it needs long and frequent walks, even if they are not daily.\nIt needs socialization and training.",
    training="Training:\nIt is a easy dog to train because it is intelligent and easily understands what is required of it.\nWith a gentle, peaceful, friendly, but consistent training, the wanted results can be achieved.",
    usefulness="Usefulness:\nIt is used to hunt large wild animals and as a companion dog.")
barzoi=Dog(
    description="Description:\nIt is a large-sized, slender dog, but at the same time, graceful and strong. The head is long, narrow, the skull is flat, rather long, with a straight, long, narrow muzzle, almost without a stop and with a big and black nose. The eyes are almond-shaped, pretty close and dark. The ears are set high, towards the back, rather small, thin and pointed at the tip. When the animal rests, the ears stay over the neck, in the shape of a rose and when the animal moves, they are erect with the tips forward. The neck is long, brawny and the back is slightly curved, becoming round towards the loins. The back legs are brawnier than the front legs, which allows it to reach remarkable speeds. The tail is placed low, long, sickle- or sword-shaped, kept low at rest or high, up to the backline, when alert. The fur has medium length, soft hair, slightly wavy or with large curls. It is especially rich around the neck, chest, backside of the legs and tail. It is shorter on the head, ears and front side of the legs. It can be any colour or combination of colours.",
    personality="Personality:\nIt is an intelligent, brave, dynamic, proud, gentle, watchful, peaceful dog, quiet in the house, sometimes stubborn, independent. It is devoted to its master, cautious and suspicious of strangers, it accepts children, but without being play mates. If they are socialized from an early age with other dogs and or other household animals, they will tend to accept them, but they will hunt any animal (smaller dog, the cat or anything else) which runs. It barks just a little, even at strangers.",
    grooming="Grooming:\nThis dog's fur needs regular combing and brushing. The hair between the footpads must be removed.",
    living_conditions="Living conditions:\nIt is a dog which feels good in a fenced space, where it can move freely and it adapts with difficulty to a flat. It is recommended to an active person with experience in raising dogs. If quiet indoors, outside it needs exercise, walks, it likes running (it runs in a typical gallop, in big leaps) in open fields or by a bike. One should take care, because the dog has the habit of catching any prey it sees. It needs socialization and training.",
    training="Training:\nThe training of this dog must be done by a person with experience, because it is not very obedient. With a firm, consistent training, without being harsh or severe, satisfying results can be achieved.",
    usefulness="Usefulness:\nIt is a dog used to hunt small and large animals, it can participate in dog races, it is a good watchdog and a peaceful companion.")

other1=Dog(
    description="Description:\n",
    personality="Personality:\n",
    grooming="Grooming:\n",
    living_conditions="Living conditions:\n",
    training="Training:\n",
    usefulness="Usefulness:\n")

other=Dog(
    description="Description:\n",
    personality="Personality:\n",
    grooming="Grooming:\n",
    living_conditions="Living conditions:\n",
    training="Training:\n",
    usefulness="Usefulness:\n")