breed_characteristics = {
    "Airedale Terrier":
        {1: "Description\n The Airedale Terrier is a large-sized, robust and wiry dog, with an elegant look.\nThe head is long, flat and conspicuous. \nThe eyes are small, dark and very expressive.\nThe ears are small, V-shaped and kept to the side, with the turn-over line slightly above the head.\nThe tail is kept erect almost vertical, and docked to two-thirds of its length.\nThe coat is double-layered with a short, hard, wiry, and slightly wavy without being curly outer layer.\nIt can be black,grey or fawn on the back (like a saddle).",
        2: "Personality\nIt is an intelligent, brave, lively, quiet, active sometimes, playful and stubborn dog. Very devoted to its owner and patient with children. It accepts other household animals but tends to dominate other dogs if it wasn't taught to accept them. Is alert in the presence of strangers.",
        3: "Grooming\nThis dog doesn't require too much grooming. The fur will be trimmed twice a year. The fur between the paw pads of the feet will be cut when necessary.",
        4: "Living condition\nThe Airedale Terrier can rezist in bad weather and likes to live outdoors, in a large space, where it can get a lot of exercise, because it has a high level of activity. He needs training and socializing.",
        5: "Training\nIt is a relatively easy dog to train, because it is intelligent and eager to learn. The training must be consistent, firm, without being rough, and it should be varied so it won’t get bored, otherwise it will become very stubborn. It likes canine sports.",
        6: "Usefulness\nIt is used for hunting wild animals (otters, martens, foxes, rabbits, wild boars, bears). It is a good watchdog and in England it is widely used as a police dog. It is a pleasant companion dog. "},
    "American Pit Bull Terrier":
        {1: "Description\nIt is a medium-sized, strong and muscular dog. It has a wide and short body, bigger in length than in height. The head is strong, broad, trapezoidal, with a long and wide muzzle but shorter than the skull (unlike the Amstaff). The cheeks, unlike those of the Amstaff, are flat. The nose is large and can have any color. The eyes are round and almond-shaped and can have any color except blue. The ears are small to medium and can be erect or semi-erect and can also be cropped. The chest is deep and less wide compared to the Amstaff. The rear legs are strong and muscular.\nThe tail is medium-sized, thick and with a pointed tip.\nThe coat is short, smooth, shiny and can have any color.",
        2: "Personality\nIs a confident dog with a tremendous taste for life. The Pitbull is very friendly with people, especially with children. It is so happy when given attention that it is willing to endure the toughest games of the children. It is unfriendly and aggressive with other dogs, especially to those of the same gender. It is the most controversial race of all, because friendly as it can be with people, it can become equally aggressive towards other dogs or other people it considers dangerous.",
        3: "Grooming\nThis dog doesn't require special care. The dead hair will be removed with a rubber brush or glove, from time to time. The master should take care of how much the dog eats during the growing period, because it is prone to obesity. The meals should be served at fixed hours. ",
        4: "Living condition\nIt is a dog with a high level of activity and feels best in a fenced yard, with an active family, with experience in raising dogs.\nIt likes to run by a bike, to play with the ball, to play fetch, to swim and to dig. It can adapt to apartment life, if it gets the daily exercise that it needs (2-3 hours daily). It needs socializing and training (mandatory), because it has a dominant character and is harder to controle.",
        5: "Training\nIt needs mandatory training , starting from an early age. It must be taught not to pull when leashed when it is a pup, to avoid having problems when it grows up and has great strengh and is hard to control. It is an intelligent, nimble dog, which understands very fast what is required.\nThe training should start at an early age because it can assimilate much more information and great results can be obtained. \nt shouldn't be trained to attack, because it has an innate aggressive character.",
        6: "Usefulness\nIt was used during the World Wars as a messenger on the battlefield. Nowadays it is more used as a watchdog and as a pet."},
    "Australian Terrier":
        {1: "Description\nIt is a small-sized dog, with a rather longer than taller body.\nThe head is long, strong, with the skull equal in length with the muzzle, with a fine stop.\nThe eyes are small and dark.\nThe ears are small, with pointed tips, kept vertical, wide apart and with little hair on them but with a tuft of hair between them, on the forehead.\nThe tail is docked at half its length and is kept high, almost vertical.\nThe fur is double-layered, with a soft, fluffy first layer and an outer layer with long, rough, straight hair.\nAround its neck the hair forms a mane and it has furry legs.",
         2: "Personality\nIt is a lively, active, clever, brave, alert, confident and curious dog by nature. Devoted and friendly to its family, it has trouble accepting strangers.\nIt gets along well with children if they do not bother it. It must be taught to live with other household animals from an early age, to avoid future conflicts.",
         3: "Grooming\nThis dog's fur must be brushed weekly and trimmed two-three times a year.",
         4: "Living condition\nThese dogs can easily adapt to different living conditions, but they should have the possibility of running and playing together with a loving family.\nThey need socialization and training.",
         5: "Training\nIt needs a firm, consistent training, that doesn't let it have its way. It likes activity, walking, running and playing.",
         6: "Usefulness\nIt is a very good pest hunter and a cheerful companion."},
    "Australian Silky Terrier":
        {1: "Description\nIt is a small-sized, harmoniously built, robust dog that has an elegant look due to its silky hair. The head is of medium length, the skull is flat, slightly longer than the muzzle and has a fine forelock on the forehead. The eyes are small, round, almond-shaped and dark.\nThe ears are V-shaped, small, set high, erect and without long hair on them.\nThe tail is kept right and must be docked short.\nThe fur has a single layer made of 12-15 cm length hair that is very soft, glossy and silky.\nThe most common variety is the bluish-grey that can have different shades, from bright to dark, with brown, but the most appreciated and desired colour is iron blue.\nThe fur is brushed with a parting on the middle of the back.\nAt birth all the dogs of this breed are black.",
         2: "Personality\nThis dog is dynamic, intelligent, eager to learn, active, lively, playful, cheerful, obedient, alert and although it is small it is very protective.\nVery devoted to its master it is loving and playful with children.\nIt is watchful with strangers whom it barks at. Accustomed from an early age to other household animals and to other dogs, it will have no problems when it grows up.",
         3: "Grooming\nThe fur must be brushed and combed daily in order to maintain it beautiful and healthy.\nThis breed rarely sheds.",
         4: "Living condition\nThis dog adapts easily to the offered living conditions, being a suitable dog for a flat, with a loving and caring family.\nIt needs socialization and training.",
         5: "Training\nThe training should be done with ease and pleasure, because it is an intelligent and obedient dog that is eager to learn and easily understands what is required of it.\nIt has a medium level of activity, it likes not too long walks and doesn't become restless if it is not taken out for a walk every day.\nIt adapts to its master - more or less active.",
         6: "Usefulness\nIt is a good mouse hunter but especially a happy and devoted companion."},
    "Cairn Terrier":
        {1: "Description\nIt is a small-sized, sturdy dog with short legs. It has a flat head, a pronounced stop, a strong muzzle and a black nose.\nThe eyes are wide apart, hazel and covered with bushy eyebrows. \nhe ears are small, triangular, slightly slating, pointy and erect. The tail is short, pointy at the tip covered in hair and carried vertically.\nThe fur is double-layered, with soft and fluffy inner layer and an outer layer made of thick, rough, not too short, straight hair.\nThe coat can have any colour except white and has darker shades on the ears, muzzle and the tip of the tail.",
         2: "Personality\nIt is a lively, very happy, playful, alert, brave, intelligent, watchful dog. It is affectionate and devoted to its master. It is loving and tolerant with children and is not aggressive with strangers. It gets along well with other household animals, even with other dogs, with some exceptions.",
         3: "Grooming\nThis dog's fur must be brushed regularly and trimmed 2-3 times a year.",
         4: "Living condition\nIt is a dog that can adapt rather easily both to outdoor life, being resistant to weather changes and to life in a flat with an active family and with the possibility of exercising and getting daily walks.\nIt needs socialization and training.",
         5: "Training\nThis dog is relatively easy to train because it is intelligent, likes to learn and to work. It needs a rigorous, firm, consistent training done in a gentle and calm voice and it shouldn't be let to do what it wants.\nIt should be socialized from an early age with other household animals and other dogs. It likes exercise and running in open spaces. It must be taught to come to its master when called, because of its hunting instincts that can make it run away.",
         6: "Usefulness\nIt is a very good hunter of rodents and small wild animals.\nIt is a perfect companion for a sportive family."},
    "West Highland White Terrier":
        {1: "Description",
         2: "Personality",
         3: "Grooming",
         4: "Living condition",
         5: "Training",
         6: "Usefulness"},
    "Norfolk Terrier":
        {1: "Description",
         2: "Personality",
         3: "Grooming",
         4: "Living condition",
         5: "Training",
         6: "Usefulness"},
    "Norwich Terrier":
        {1: "Description",
         2: "Personality",
         3: "Grooming",
         4: "Living condition",
         5: "Training",
         6: "Usefulness"},
    "Scottish Terrier":
        {1: "Description",
         2: "Personality",
         3: "Grooming",
         4: "Living condition",
         5: "Training",
         6: "Usefulness"},
    "Scottish Sky Terrier":
        {1: "Description",
         2: "Personality",
         3: "Grooming",
         4: "Living condition",
         5: "Training",
         6: "Usefulness"},
    "Irish Wolfhound":
        {1: "Description\nIt is a large-sized, brawny, sturdy dog but with supple movements.\nIt has a long head, the skull is not too wide with a long, slightly pointed muzzle and a black nose.\nThe eyes are oval, medium-sized and dark. The ears are small, delicate and folded in the shape of a rose. It has a long, brawny, strong neck. The tail is long, slightly bent and of medium thick.\nThe fur is double-layered with a short and fluffy inner layer, and an outer layer that has medium length, thick, rough, pointy, wiry hair that is slightly longer on the head where it forms eyebrows and a bit of beard.\nThe colour of the coat can be grey, red mixed with white and black, reddish, black, light brown and white.",
         2: "Personality\n It is an intelligent, brave, dynamic, sensitive, peaceful dog.\nIt is affectionate and very attached to its master and his family, patient with children and pretty friendly with everyone.\nIf it is socialized from an early age, it will have no problems with other dogs and other animals.\nIt barks very little.",
         3: "Grooming\nThis dog's fur must be brushed and combed regularly.\nAlso, once or twice a year it will be trimmed to remove excess hair.\nDuring the growing period it should be properly fed and shouldn't be forced to exercise more than it wants.\nIt finalizes its growth at the age of 2 years.",
         4: "Living condition\nIt is a dog which adapts to the offered conditions, but it feels best outdoors in a well-fenced yard where it can move freely.\nKept in a house or in a spacious flat (it is a large and tall dog), it needs long and frequent walks, even if they are not daily.\nIt needs socialization and training.",
         5: "Training\nIt is a easy dog to train because it is intelligent and easily understands what is required of it.\nWith a gentle, peaceful, friendly, but consistent training, the wanted results can be achieved.",
         6: "Usefulness\nIt is used to hunt large wild animals and as a companion dog."
        }
}